import React,{useMemo,useState} from 'react';
import {Card,Page,Shell,Status} from './PharmacyShell';
import {usePharmacy} from './PharmacyContext';
const filters=['All','Verification','Preparing','Ready','Dispatched','Completed','Cancelled']; const nextStatus={Verification:'Preparing',Preparing:'Ready',Ready:'Dispatched',Dispatched:'Completed'};
const empty={patient:'',patientId:'',prescription:'',medicines:'1',amount:'',priority:'Normal'};
export default function PharmacyOrders(){const {orders,updateOrderStatus,createOrder,patients}=usePharmacy();const [filter,setFilter]=useState('All');const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [form,setForm]=useState(empty);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const rows=useMemo(()=>orders.filter(o=>(filter==='All'||o.status===filter)&&`${o.id} ${o.patient} ${o.prescription||''}`.toLowerCase().includes(search.toLowerCase())),[orders,filter,search]);
 const submit=async e=>{e.preventDefault();setError('');setSaving(true);try{await createOrder({...form,medicines:Number(form.medicines),amount:Number(form.amount||0)});setForm(empty);setOpen(false);}catch(err){setError(err.message)}finally{setSaving(false)}};
 return <Shell><Page title="Orders" subtitle="Create and process real pharmacy orders." actions={<button className="primary-button" onClick={()=>setOpen(true)}>+ New Order</button>}/><Card title="Order Management" subtitle={`${rows.length} orders match your filters`}><div className="toolbar"><input className="pharmacy-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, patient or prescription..."/><div className="order-filters">{filters.map(f=><button key={f} className={`filter-button ${filter===f?'active':''}`} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="orders-table"><div className="order-row order-header"><span>ORDER</span><span>PATIENT</span><span>MEDICINES</span><span>AMOUNT</span><span>STATUS</span><span>ACTION</span></div>{rows.map(o=><div className="order-row" key={o.id}><div><strong>#{o.id}</strong><small>{o.created}</small></div><span>{o.patient}</span><span className="muted">{o.medicines} medicines</span><strong>₹{Number(o.amount).toLocaleString('en-IN')}</strong><Status>{o.status}</Status><button className="table-action" disabled={!nextStatus[o.status]} onClick={()=>updateOrderStatus(o.id,nextStatus[o.status])}>{nextStatus[o.status]?`Mark ${nextStatus[o.status]}`:'View'}</button></div>)}</div>{rows.length===0&&<div className="empty-state"><div>⌕</div><strong>No orders found</strong><span>Try another filter or create a new order.</span></div>}</Card>
 {open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><form className="dashboard-card modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><div className="card-header"><div><h2>Create New Order</h2><p>Record a real pharmacy transaction.</p></div><button type="button" className="close-button" onClick={()=>setOpen(false)}>×</button></div>{error&&<div className="form-error">{error}</div>}<div className="form-grid"><div className="form-field"><label>Patient name *</label><input list="patient-list" required value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}/><datalist id="patient-list">{patients.map(p=><option key={p.id} value={p.name}/>)}</datalist></div><div className="form-field"><label>Patient ID</label><input value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}/></div><div className="form-field"><label>Prescription ID</label><input value={form.prescription} onChange={e=>setForm({...form,prescription:e.target.value})}/></div><div className="form-field"><label>Number of medicines</label><input type="number" min="1" required value={form.medicines} onChange={e=>setForm({...form,medicines:e.target.value})}/></div><div className="form-field"><label>Total amount (₹)</label><input type="number" min="0" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div className="form-field"><label>Priority</label><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Normal</option><option>Urgent</option></select></div></div><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Creating...':'Create Order'}</button></div></form></div>}
 </Shell>}
