'use client';

import { useCallback, useEffect, useState } from 'react';
import { FilePlus2, Printer, Save, ShieldCheck } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { useTranslations } from 'next-intl';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { useHospital } from '@/lib/hospital/HospitalProvider';
import { callRpc } from '@/lib/hospital/api';
import { supabase } from '@/lib/supabase-client';

type Consultation={id:string;patient_id:string;status:'draft'|'final';version:number;complaint:string|null;assessment:string|null;plan:string|null;advice:string|null};
type Context={previous_visits:Array<{visit_date:string}>;current_treatment:{plan:string;advice:string}|null;pending_investigations:Array<{type:string;status:string;expected_from:string|null;expected_to:string|null}>;prior_prescriptions:Array<{notes:string|null;items:Array<{medicine_name:string;dose:string|null;frequency:string|null;duration:string|null}>}>;history:Array<{complaint:string|null;assessment:string|null;plan:string|null;finalised_at:string|null}>};
type Department={id:string;name:string};
type Doctor={id:string;doctor_name:string;department_id:string|null};
type RxItem={medicine_name:string;dose:string;frequency:string;duration:string;instructions:string};
const EMPTY_CONTEXT:Context={previous_visits:[],current_treatment:null,pending_investigations:[],prior_prescriptions:[],history:[]};

export function ConsultDrawer({open,onOpenChange,entryId,patientName,token}:{open:boolean;onOpenChange:(open:boolean)=>void;entryId:string;patientName:string;token:number}){
  const t=useTranslations('hospitalOps');const {org}=useHospital();const [consult,setConsult]=useState<Consultation|null>(null);const [context,setContext]=useState<Context>(EMPTY_CONTEXT);const [tab,setTab]=useState<'context'|'notes'|'prescription'|'investigations'|'followup'>('context');const [fields,setFields]=useState({complaint:'',assessment:'',plan:'',advice:''});const [items,setItems]=useState<RxItem[]>([{medicine_name:'',dose:'',frequency:'',duration:'',instructions:''}]);const [rxNotes,setRxNotes]=useState('');const [departments,setDepartments]=useState<Department[]>([]);const [doctors,setDoctors]=useState<Doctor[]>([]);const [departmentId,setDepartmentId]=useState('');const [doctorId,setDoctorId]=useState('');const [priority,setPriority]=useState('routine');const [reason,setReason]=useState('');const [followDate,setFollowDate]=useState('');const [followAdvice,setFollowAdvice]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);

  const load=useCallback(async()=>{if(!open||!org)return;setBusy(true);setError('');try{const draft=await callRpc<Consultation>('start_consultation_record',{p_entry_id:entryId});setConsult(draft);setFields({complaint:draft.complaint??'',assessment:draft.assessment??'',plan:draft.plan??'',advice:draft.advice??''});const ctx=await callRpc<Context>('get_consultation_context',{p_hospital_id:org.id,p_patient_id:draft.patient_id});setContext(ctx??EMPTY_CONTEXT);const [depResult,doctorResult]=await Promise.all([supabase.from('hospital_departments').select('id,name').eq('hospital_id',org.id).eq('is_active',true).eq('department_type','clinical'),supabase.from('hospital_doctors').select('id,doctor_name,department_id').eq('hospital_id',org.id).eq('is_active',true)]);if(depResult.error)throw depResult.error;if(doctorResult.error)throw doctorResult.error;setDepartments((depResult.data??[]) as Department[]);setDoctors((doctorResult.data??[]) as Doctor[]);}catch(caught){setError(caught instanceof Error?caught.message:t('consultationLoadFailed'));}finally{setBusy(false);}},[open,org,entryId,t]);
  useEffect(()=>{void load();},[load]);

  const save=useCallback(async()=>{if(!consult||consult.status!=='draft')return;setSaved(false);try{const updated=await callRpc<Consultation>('save_consultation_draft',{p_id:consult.id,p_fields:fields});setConsult(updated);setSaved(true);}catch(caught){setError(caught instanceof Error?caught.message:t('draftSaveFailed'));}},[consult,fields,t]);
  useEffect(()=>{if(!consult||consult.status!=='draft')return;const timer=setTimeout(()=>void save(),5000);return()=>clearTimeout(timer);},[consult,fields,save]);
  const finalize=async()=>{if(!consult||!window.confirm(t('confirmFinalize')))return;setBusy(true);try{const result=await callRpc<Consultation>('finalize_consultation',{p_id:consult.id});setConsult(result);}catch(caught){setError(caught instanceof Error?caught.message:t('finalizeFailed'));}finally{setBusy(false);}};
  const amend=async()=>{if(!consult)return;setBusy(true);try{const next=await callRpc<Consultation>('amend_consultation',{p_id:consult.id});setConsult(next);setFields({complaint:next.complaint??'',assessment:next.assessment??'',plan:next.plan??'',advice:next.advice??''});}catch(caught){setError(caught instanceof Error?caught.message:t('amendFailed'));}finally{setBusy(false);}};
  const savePrescription=async()=>{if(!consult)return;setBusy(true);try{await callRpc('create_prescription',{p_consultation_id:consult.id,p_items:items.filter((item)=>item.medicine_name.trim()),p_notes:rxNotes});setError('');}catch(caught){setError(caught instanceof Error?caught.message:t('prescriptionFailed'));}finally{setBusy(false);}};
  const printPrescription=()=>{const pdf=new jsPDF();pdf.setFontSize(16);pdf.text(org?.name??'Hospital',16,18);pdf.setFontSize(11);pdf.text(`${patientName} · ${t('queueToken')} #${token}`,16,28);pdf.text(t('prescription'),16,40);items.filter((item)=>item.medicine_name.trim()).forEach((item,index)=>pdf.text(`${index+1}. ${item.medicine_name} · ${item.dose} · ${item.frequency} · ${item.duration}`,16,52+index*9));pdf.save(`prescription-${token}.pdf`);};
  const createReferral=async()=>{if(!consult||!departmentId)return;setBusy(true);try{await callRpc('create_referral',{p_consultation_id:consult.id,p_to_department_id:departmentId,p_to_doctor_id:doctorId||null,p_priority:priority,p_reason:reason});setReason('');}catch(caught){setError(caught instanceof Error?caught.message:t('referralFailed'));}finally{setBusy(false);}};
  const createFollowUp=async()=>{if(!consult)return;setBusy(true);try{await callRpc('schedule_follow_up',{p_consultation_id:consult.id,p_due_date:followDate,p_advice:followAdvice,p_depends_on_order_id:null});setFollowAdvice('');}catch(caught){setError(caught instanceof Error?caught.message:t('followUpFailed'));}finally{setBusy(false);}};

  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{patientName} · #{token}</SheetTitle><SheetDescription>{t('consultationDrawerDescription')}</SheetDescription></SheetHeader>
    {error&&<p role="alert" className="mt-3 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <nav className="mt-5 flex gap-1 overflow-x-auto border-b">{(['context','notes','prescription','investigations','followup'] as const).map((key)=><button key={key} onClick={()=>setTab(key)} className={`min-h-10 shrink-0 border-b-2 px-2 text-xs font-semibold ${tab===key?'border-teal-800 text-teal-900':'border-transparent text-slate-600'}`}>{t(`consultTab.${key}` as 'consultTab.context')}</button>)}</nav>
    {tab==='context'&&<section className="mt-4 space-y-4"><Info title={t('currentTreatment')} body={context.current_treatment?.plan??t('noTreatmentContext')}/><section className="rounded-lg border p-3"><h3 className="font-semibold">{t('previousVisits')}</h3>{context.previous_visits.slice(0,6).map((visit,index)=><p key={`${visit.visit_date}-${index}`} className="mt-2 text-sm text-slate-600">{visit.visit_date}</p>)}</section><section className="rounded-lg border p-3"><h3 className="font-semibold">{t('priorPrescriptions')}</h3>{context.prior_prescriptions.slice(0,5).map((prescription,index)=><p key={index} className="mt-2 text-sm text-slate-600">{prescription.items.map((item)=>`${item.medicine_name} ${item.dose??''}`).join(' · ')}</p>)}</section><section className="rounded-lg border p-3"><h3 className="font-semibold">{t('pendingInvestigations')}</h3>{context.pending_investigations.map((order,index)=><p key={index} className="mt-2 text-sm text-slate-600">{order.type} · {t(`status.${order.status}` as 'status.pending')}</p>)}</section></section>}
    {tab==='notes'&&<section className="mt-4 space-y-3">{(['complaint','assessment','plan','advice'] as const).map((key)=><label key={key} className="block text-sm font-medium text-slate-700">{t(`consultField.${key}` as 'consultField.complaint')}<textarea rows={3} value={fields[key]} disabled={consult?.status==='final'} onChange={(event)=>setFields((current)=>({...current,[key]:event.target.value}))} className="mt-1 w-full rounded-md border border-slate-300 p-3 disabled:bg-slate-50"/></label>)}<div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-slate-500">{saved?t('draftSaved'):t('autosaving')}</span><div className="flex gap-2">{consult?.status==='draft'?<><button onClick={()=>void save()} disabled={busy} className="inline-flex min-h-10 items-center gap-2 rounded-md border px-3 text-sm"><Save className="h-4 w-4"/>{t('saveDraft')}</button><button onClick={()=>void finalize()} disabled={busy} className="min-h-10 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{t('finalizeConsultation')}</button></>:<><span className="inline-flex items-center gap-1 text-sm text-emerald-800"><ShieldCheck className="h-4 w-4"/>{t('finalizedReadOnly')}</span><button onClick={()=>void amend()} disabled={busy} className="min-h-10 rounded-md border px-3 text-sm">{t('amendConsultation')}</button></>}</div></div></section>}
    {tab==='prescription'&&<section className="mt-4 space-y-3">{items.map((item,index)=><div key={index} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-2"><Field label={t('medicine')} value={item.medicine_name} change={(value)=>updateItem(index,'medicine_name',value)}/><Field label={t('dose')} value={item.dose} change={(value)=>updateItem(index,'dose',value)}/><Field label={t('frequency')} value={item.frequency} change={(value)=>updateItem(index,'frequency',value)}/><Field label={t('duration')} value={item.duration} change={(value)=>updateItem(index,'duration',value)}/><Field label={t('instructions')} value={item.instructions} change={(value)=>updateItem(index,'instructions',value)}/></div>)}<button disabled={consult?.status==='final'} onClick={()=>setItems((current)=>[...current,{medicine_name:'',dose:'',frequency:'',duration:'',instructions:''}])} className="min-h-10 rounded-md border px-3 text-sm"><FilePlus2 className="mr-2 inline h-4 w-4"/>{t('addMedicine')}</button><textarea value={rxNotes} onChange={(event)=>setRxNotes(event.target.value)} placeholder={t('prescriptionNotes')} rows={2} className="w-full rounded-md border p-3 text-sm"/><div className="flex gap-2"><button disabled={busy||consult?.status==='final'} onClick={()=>void savePrescription()} className="min-h-10 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{t('savePrescription')}</button><button onClick={printPrescription} className="min-h-10 rounded-md border px-3 text-sm"><Printer className="mr-2 inline h-4 w-4"/>{t('printPrescription')}</button></div></section>}
    {tab==='investigations'&&<section className="mt-4 space-y-3">{context.pending_investigations.length?context.pending_investigations.map((order,index)=><Info key={index} title={order.type} body={`${t(`status.${order.status}` as 'status.pending')} · ${order.expected_from??'—'} – ${order.expected_to??'—'}`}/>):<Info title={t('investigations')} body={t('noPendingInvestigations')}/>}</section>}
    {tab==='followup'&&<section className="mt-4 space-y-4"><div className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">{t('referPatient')}</h3><Select label={t('department')} value={departmentId} change={setDepartmentId} options={departments.map((item)=>({id:item.id,label:item.name}))}/><Select label={t('doctor')} value={doctorId} change={setDoctorId} options={doctors.filter((item)=>!departmentId||item.department_id===departmentId).map((item)=>({id:item.id,label:item.doctor_name}))} optional/><Select label={t('priority')} value={priority} change={setPriority} options={['routine','urgent','clinically_priority','emergency'].map((item)=>({id:item,label:t(`status.${item}` as 'status.routine')}))}/><Field label={t('reason')} value={reason} change={setReason}/><button disabled={busy||!departmentId||reason.trim().length<3||consult?.status==='final'} onClick={()=>void createReferral()} className="min-h-10 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{t('createReferral')}</button></div><div className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">{t('scheduleFollowUp')}</h3><Field label={t('dueDate')} type="date" value={followDate} change={setFollowDate}/><Field label={t('advice')} value={followAdvice} change={setFollowAdvice}/><button disabled={busy||!followDate||!followAdvice||consult?.status==='final'} onClick={()=>void createFollowUp()} className="min-h-10 rounded-md border px-4 text-sm font-semibold">{t('scheduleFollowUp')}</button></div></section>}
  </SheetContent></Sheet>;

  function updateItem(index:number,key:keyof RxItem,value:string){setItems((current)=>current.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));}
}
function Info({title,body}:{title:string;body:string}){return <article className="rounded-lg border p-3"><h3 className="text-sm font-semibold text-slate-900">{title}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{body}</p></article>}
function Field({label,value,change,type='text'}:{label:string;value:string;change:(value:string)=>void;type?:string}){return <label className="block text-sm font-medium text-slate-700">{label}<input type={type} value={value} onChange={(event)=>change(event.target.value)} className="mt-1 h-10 w-full rounded-md border px-3"/></label>}
function Select({label,value,change,options,optional=false}:{label:string;value:string;change:(value:string)=>void;options:Array<{id:string;label:string}>;optional?:boolean}){return <label className="block text-sm font-medium">{label}<select required={!optional} value={value} onChange={(event)=>change(event.target.value)} className="mt-1 h-10 w-full rounded-md border px-3"><option value="">—</option>{options.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}
