import React from 'react';
import {Search,Plus,ChevronRight,Video,MapPin,AlertTriangle,CheckCircle2,X,FileText} from 'lucide-react';
export function PageHeader({title,subtitle,action,actionLabel='Add new',secondary}){return <div className="page-header"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="header-actions">{secondary}{action&&<button className="btn primary" onClick={action}><Plus size={17}/>{actionLabel}</button>}</div></div>}
export function Badge({children,tone='neutral'}){return <span className={'badge '+tone}>{children}</span>}
export function Modal({title,onClose,children,footer,wide=false}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={'modal '+(wide?'modal-wide':'')}><div className="modal-head"><h3>{title}</h3><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-foot">{footer}</div>}</div></div>}
export function Empty({text}){return <div className="empty"><FileText size={28}/><p>{text}</p></div>}
export function SearchBox({value,onChange,placeholder='Search...'}){return <div className="search-box"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function StatCard({icon:Icon,label,value,sub,tone='teal',onClick}){return <div className={'stat-card '+(onClick?'clickable':'')} onClick={onClick}><div className={'stat-icon '+tone}><Icon size={19}/></div><div><div className="stat-label">{label}</div><div className="stat-value">{value}</div>{sub&&<div className="stat-sub">{sub}</div>}</div></div>}
export function AppointmentRow({item,patient,onAction}){return <div className="appointment-row"><div className="time">{item.time}</div><div className="appt-icon">{item.mode==='Video'?<Video size={17}/>:<MapPin size={17}/>}</div><div className="appt-main"><strong>{patient?.name||'Unknown patient'}</strong><span>{item.type} · {item.mode}</span></div><Badge tone={item.status==='Pending'?'warning':item.status==='Cancelled'?'danger':'success'}>{item.status}</Badge>{onAction&&<button className="text-btn" onClick={onAction}>Open <ChevronRight size={15}/></button>}</div>}
export function AlertRow({patient,kind='warning',text,onClick}){return <button className="alert-row" onClick={onClick}><span className={'alert-icon '+kind}>{kind==='success'?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>}</span><span className="alert-main"><strong>{patient?.name}</strong><small>{text}</small></span><ChevronRight size={16}/></button>}
export function FormField({label,...props}){return <label className="field"><span>{label}</span>{props.type==='textarea'?<textarea {...props}/>:<input {...props}/>}</label>}
export function SelectField({label,children,...props}){return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>}
export function Progress({value}){return <div className="progress"><span style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
