'use client';

import { useCallback, useEffect, useState } from 'react';
import { FileSearch, FlaskConical, Settings2, Timer, Users } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { supabase } from '@/lib/supabase-client';
import { useHospital } from '@/lib/hospital/HospitalProvider';
import { callRpc } from '@/lib/hospital/api';
import { DataTable, ErrorPanel, KpiCard, StatusChip } from '@/components/hospital/ui-kit';
import { formatHospitalDate } from '@/lib/hospital/format';

type Order={id:string;patient_id:string;type_id:string;priority:string;status:string;scheduled_for:string|null;expected_report_from:string|null;expected_report_to:string|null;needs_reschedule:boolean;ordered_at:string};
type Type={id:string;name:string;category:string;expected_report_min_days:number;expected_report_max_days:number;is_active:boolean};
type Resource={id:string;type_id:string;name:string;status:string;slots_per_day:number};
type Tab='orders'|'capacity'|'waitlist'|'configuration';

export function HospitalInvestigationsPage(){
  const t=useTranslations('hospitalOps');const {org,can}=useHospital();const [tab,setTab]=useState<Tab>('orders');
  const [orders,setOrders]=useState<Order[]>([]);const [types,setTypes]=useState<Type[]>([]);const [resources,setResources]=useState<Resource[]>([]);const [waitlist,setWaitlist]=useState<Array<{id:string;order_id:string;type_id:string;priority_rank:number;status:string;joined_at:string}>>([]);
  const [loading,setLoading]=useState(true);const [technical,setTechnical]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [filter,setFilter]=useState('all');const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!org)return;setLoading(true);setError(null);try{const [orderResult,typeResult,resourceResult,waitResult]=await Promise.all([supabase.from('investigation_orders').select('id,patient_id,type_id,priority,status,scheduled_for,expected_report_from,expected_report_to,needs_reschedule,ordered_at').eq('hospital_id',org.id).order('ordered_at',{ascending:false}),supabase.from('investigation_types').select('id,name,category,expected_report_min_days,expected_report_max_days,is_active').eq('hospital_id',org.id).order('name'),supabase.from('investigation_resources').select('id,type_id,name,status,slots_per_day').eq('hospital_id',org.id),supabase.from('investigation_waitlist').select('id,order_id,type_id,priority_rank,status,joined_at').eq('hospital_id',org.id).eq('status','waiting').order('priority_rank').order('joined_at')]);for(const result of [orderResult,typeResult,resourceResult,waitResult])if(result.error)throw result.error;setOrders((orderResult.data??[]) as Order[]);setTypes((typeResult.data??[]) as Type[]);setResources((resourceResult.data??[]) as Resource[]);setWaitlist((waitResult.data??[]) as typeof waitlist);setTechnical(null);}catch(caught){setError(t('investigationsLoadFailed'));setTechnical(caught instanceof Error?caught.message:String(caught));}finally{setLoading(false);}},[org,t]);
  useEffect(()=>{void load();},[load]);
  const advance=async(order:Order,to:string)=>{setBusy(true);try{await callRpc('investigation_advance',{p_order_id:order.id,p_to:to,p_payload:{}});await load();}catch(caught){setError(caught instanceof Error?caught.message:t('operationFailed'));}finally{setBusy(false);}};
  if(!org)return null;const typeById=new Map(types.map((item)=>[item.id,item]));const visible=orders.filter((item)=>filter==='all'||item.status===filter);const capacity=types.map((type)=>({type,...resources.filter((resource)=>resource.type_id===type.id&&resource.status==='active').reduce((sum,resource)=>({...sum,daily:sum.daily+resource.slots_per_day}),{daily:0})}));
  return <div className="space-y-5"><header><h1 className="text-2xl font-semibold text-slate-950">{t('investigationsTitle')}</h1><p className="mt-1 text-sm text-slate-600">{t('investigationsDescription')}</p></header><nav className="flex gap-1 overflow-x-auto border-b">{(['orders','capacity','waitlist','configuration'] as const).map((key)=><button key={key} onClick={()=>setTab(key)} className={`min-h-11 shrink-0 border-b-2 px-3 text-sm font-semibold ${tab===key?'border-teal-800 text-teal-900':'border-transparent text-slate-600'}`}>{t(`investigationTab.${key}` as 'investigationTab.orders')}</button>)}</nav>
    {error&&<ErrorPanel message={error} technicalDetails={technical} onRetry={()=>void load()} retryLabel={t('retry')} detailsLabel={t('showTechnicalDetails')}/>}
    {tab==='orders'&&<div className="space-y-3"><div className="flex flex-wrap gap-3"><label className="text-sm">{t('filterStatus')}<select value={filter} onChange={(event)=>setFilter(event.target.value)} className="ml-2 h-10 rounded-md border px-2"><option value="all">{t('allStatuses')}</option>{['ordered','waitlisted','offered','scheduled','checked_in','performed','processing','report_ready','doctor_reviewed','cancelled'].map((status)=><option key={status}>{status}</option>)}</select></label></div>{loading?<div className="h-56 animate-pulse rounded-xl bg-slate-100"/>:<DataTable><thead className="bg-slate-50 text-xs text-slate-600"><tr>{['patient','investigation','priority','status','expectedReport','actions'].map((key)=><th className="px-3 py-3" key={key}>{t(key as 'patient')}</th>)}</tr></thead><tbody className="divide-y">{visible.map((order)=><tr key={order.id}><td className="px-3 py-3">{order.patient_id.slice(0,8)}</td><td className="px-3 py-3">{typeById.get(order.type_id)?.name??'—'}{order.needs_reschedule&&<p className="text-xs font-semibold text-amber-800">{t('needsReschedule')}</p>}</td><td className="px-3 py-3"><StatusChip code={order.priority}/></td><td className="px-3 py-3"><StatusChip code={order.status}/></td><td className="px-3 py-3">{order.expected_report_from&&order.expected_report_to?`${order.expected_report_from} – ${order.expected_report_to}`:'—'}</td><td className="px-3 py-3"><div className="flex flex-wrap gap-1">{order.status==='scheduled'&&can('orders.pipeline')&&<button disabled={busy} onClick={()=>void advance(order,'checked_in')} className="min-h-9 rounded-md border px-2 text-xs">{t('checkIn')}</button>}{order.status==='checked_in'&&can('orders.pipeline')&&<button disabled={busy} onClick={()=>void advance(order,'performed')} className="min-h-9 rounded-md border px-2 text-xs">{t('markPerformed')}</button>}{order.status==='processing'&&can('orders.pipeline')&&<button disabled={busy} onClick={()=>void advance(order,'report_ready')} className="min-h-9 rounded-md border px-2 text-xs">{t('markReportReady')}</button>}</div></td></tr>)}</tbody></DataTable>}</div>}
    {tab==='capacity'&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><KpiCard icon={FlaskConical} label={t('investigationTypes')} value={types.length}/><KpiCard icon={Timer} label={t('dailyCapacity')} value={capacity.reduce((sum,item)=>sum+item.daily,0)}/><KpiCard icon={Users} label={t('waitingList')} value={waitlist.length} tone="amber"/></div><DataTable><thead className="bg-slate-50 text-xs text-slate-600"><tr>{['investigation','dailyCapacity','resources','status'].map((key)=><th className="px-3 py-3" key={key}>{t(key as 'investigation')}</th>)}</tr></thead><tbody className="divide-y">{capacity.map(({type,daily})=><tr key={type.id}><td className="px-3 py-3 font-medium">{type.name}</td><td className="px-3 py-3">{daily}</td><td className="px-3 py-3">{resources.filter((resource)=>resource.type_id===type.id&&resource.status==='active').length}</td><td className="px-3 py-3"><StatusChip code={daily?'available':'blocked'}/></td></tr>)}</tbody></DataTable></div>}
    {tab==='waitlist'&&<DataTable><thead className="bg-slate-50 text-xs text-slate-600"><tr>{['investigation','patient','priority','joinedAt'].map((key)=><th key={key} className="px-3 py-3">{t(key as 'investigation')}</th>)}</tr></thead><tbody className="divide-y">{waitlist.map((item)=><tr key={item.id}><td className="px-3 py-3">{typeById.get(item.type_id)?.name??'—'}</td><td className="px-3 py-3">{item.order_id.slice(0,8)}</td><td className="px-3 py-3"><StatusChip code={['emergency','clinically_priority','urgent','routine'][item.priority_rank]}/></td><td className="px-3 py-3">{formatHospitalDate(item.joined_at,org.timezone)}</td></tr>)}</tbody></DataTable>}
    {tab==='configuration'&&<div className="grid gap-3 md:grid-cols-2">{types.map((type)=><article key={type.id} className="rounded-xl border bg-white p-4"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{type.name}</h2><p className="text-sm text-slate-600">{type.category} · {type.expected_report_min_days}-{type.expected_report_max_days} {t('workingDays')}</p></div><Settings2 className="h-5 w-5 text-teal-800"/></div><p className="mt-3 text-xs text-slate-500">{resources.filter((resource)=>resource.type_id===type.id).map((resource)=>`${resource.name} (${resource.slots_per_day})`).join(' · ')||t('noResources')}</p></article>)}</div>}
    {!loading&&orders.length===0&&tab==='orders'&&<div className="rounded-xl border border-dashed p-8 text-center"><FileSearch className="mx-auto h-8 w-8 text-teal-800"/><p className="mt-2 text-sm text-slate-600">{t('noInvestigationOrders')}</p></div>}
  </div>;
}
