'use client';

import { useCallback, useEffect, useState } from 'react';
import { BedDouble, Building2, Users } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { supabase } from '@/lib/supabase-client';
import { useHospital } from '@/lib/hospital/HospitalProvider';
import { callRpc } from '@/lib/hospital/api';
import { ErrorPanel, KpiCard, StatusChip } from '@/components/hospital/ui-kit';
import { formatHospitalDate } from '@/lib/hospital/format';

type Ward={id:string;name:string;is_active:boolean;is_demo:boolean};type Bed={id:string;ward_id:string;bed_label:string;status:string;is_demo:boolean};
type Admission={id:string;patient_id:string;ward_id:string;bed_id:string;admitting_doctor_id:string|null;reason:string|null;status:string;admitted_at:string;is_demo:boolean};
type Patient={id:string;patient_identifier:string;name:string};type Doctor={id:string;doctor_name:string};

export function HospitalAdmissionsPage(){
  const t=useTranslations('hospitalOps');const {org,can}=useHospital();const [wards,setWards]=useState<Ward[]>([]);const [beds,setBeds]=useState<Bed[]>([]);const [admissions,setAdmissions]=useState<Admission[]>([]);const [patients,setPatients]=useState<Patient[]>([]);const [doctors,setDoctors]=useState<Doctor[]>([]);const [loading,setLoading]=useState(true);const [technical,setTechnical]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const [dialog,setDialog]=useState<'admit'|'ward'|null>(null);const [patientId,setPatientId]=useState('');const [wardId,setWardId]=useState('');const [bedId,setBedId]=useState('');const [doctorId,setDoctorId]=useState('');const [reason,setReason]=useState('');const [wardName,setWardName]=useState('');const [bedCount,setBedCount]=useState('10');
  const load=useCallback(async()=>{if(!org)return;setLoading(true);setError(null);try{const [wardResult,bedResult,admissionResult,patientResult,doctorResult]=await Promise.all([supabase.from('hospital_wards').select('id,name,is_active,is_demo').eq('hospital_id',org.id).order('name'),supabase.from('hospital_beds').select('id,ward_id,bed_label,status,is_demo').eq('hospital_id',org.id).order('bed_label'),supabase.from('hospital_admissions').select('id,patient_id,ward_id,bed_id,admitting_doctor_id,reason,status,admitted_at,is_demo').eq('hospital_id',org.id).eq('status','admitted').order('admitted_at',{ascending:false}),supabase.from('hospital_patients').select('id,patient_identifier,name').eq('hospital_id',org.id).order('name').limit(300),supabase.from('hospital_doctors').select('id,doctor_name').eq('hospital_id',org.id).eq('is_active',true).order('doctor_name')]);for(const result of [wardResult,bedResult,admissionResult,patientResult,doctorResult])if(result.error)throw result.error;setWards((wardResult.data??[]) as Ward[]);setBeds((bedResult.data??[]) as Bed[]);setAdmissions((admissionResult.data??[]) as Admission[]);setPatients((patientResult.data??[]) as Patient[]);setDoctors((doctorResult.data??[]) as Doctor[]);setTechnical(null);}catch(caught){setError(t('admissionsLoadFailed'));setTechnical(caught instanceof Error?caught.message:String(caught));}finally{setLoading(false);}},[org,t]);
  useEffect(()=>{void load();},[load]);
  const run=async(name:string,args:Record<string,unknown>)=>{setBusy(true);setError(null);try{await callRpc(name,args);await load();}catch(caught){setError(caught instanceof Error?caught.message:t('operationFailed'));}finally{setBusy(false);}};
  const admit=(event:React.FormEvent)=>{event.preventDefault();if(!org)return;void run('admit_patient',{p_hospital_id:org.id,p_patient_id:patientId,p_ward_id:wardId,p_bed_id:bedId,p_doctor_id:doctorId||null,p_reason:reason||null}).then(()=>setDialog(null));};
  const createWard=(event:React.FormEvent)=>{event.preventDefault();if(!org)return;void run('create_ward_with_beds',{p_hospital_id:org.id,p_name:wardName,p_bed_count:Number(bedCount)}).then(()=>setDialog(null));};
  const total=beds.length;const occupied=beds.filter((bed)=>bed.status==='occupied').length;const available=beds.filter((bed)=>bed.status==='available').length;const cleaning=beds.filter((bed)=>bed.status==='cleaning').length;const blocked=beds.filter((bed)=>bed.status==='blocked').length;const patientById=new Map(patients.map((item)=>[item.id,item]));const bedById=new Map(beds.map((item)=>[item.id,item]));
  if(!org)return null;
  return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold text-slate-950">{t('admissionsTitle')}</h1><p className="mt-1 text-sm text-slate-600">{t('admissionsDescription')}</p></div><div className="flex gap-2"><button disabled={!can('admissions.manage')} onClick={()=>setDialog('admit')} className="min-h-11 rounded-lg bg-teal-800 px-4 text-sm font-semibold text-white disabled:opacity-50">{t('admitPatient')}</button><button disabled={!can('config.manage')} onClick={()=>setDialog('ward')} className="min-h-11 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold disabled:opacity-50">{t('addWard')}</button></div></header>
    {error&&<ErrorPanel message={error} technicalDetails={technical} onRetry={()=>void load()} retryLabel={t('retry')} detailsLabel={t('showTechnicalDetails')}/>}
    {loading?<div className="grid gap-3 sm:grid-cols-4">{[0,1,2,3].map((i)=><div className="h-28 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard icon={BedDouble} label={t('totalBeds')} value={total}/><KpiCard icon={Users} label={t('occupiedBeds')} value={occupied}/><KpiCard icon={BedDouble} label={t('availableBeds')} value={available}/><KpiCard icon={Building2} label={t('occupancyRate')} value={total?`${Math.round(occupied/total*100)}%`:'0%'} hint={`${cleaning} ${t('cleaning').toLowerCase()} · ${blocked} ${t('blocked').toLowerCase()}`}/></div>}
    <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><section className="space-y-3"><h2 className="text-lg font-semibold">{t('wardBedMap')}</h2>{wards.map((ward)=><article key={ward.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">{ward.name}</h3>{ward.is_demo&&<span className="rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-900">{t('demo')}</span>}</div><div className="grid grid-cols-4 gap-2 sm:grid-cols-6">{beds.filter((bed)=>bed.ward_id===ward.id).map((bed)=><button key={bed.id} disabled={!can('admissions.manage')||busy||bed.status==='occupied'} onClick={()=>void run('set_bed_status',{p_bed_id:bed.id,p_status:bed.status==='blocked'||bed.status==='cleaning'?'available':'blocked'})} className={`min-h-14 rounded-lg border p-2 text-center text-xs font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-700 disabled:cursor-not-allowed ${bed.status==='available'?'border-emerald-200 bg-emerald-50 text-emerald-800':bed.status==='occupied'?'border-sky-200 bg-sky-50 text-sky-800':bed.status==='cleaning'?'border-amber-200 bg-amber-50 text-amber-900':'border-rose-200 bg-rose-50 text-rose-800'}`}><span className="block">{bed.bed_label}</span><span className="mt-1 block font-normal">{t(`status.${bed.status}` as 'status.available')}</span></button>)}</div></article>)}{wards.length===0&&!loading&&<div className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-600">{t('noWards')}</div>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-lg font-semibold">{t('currentAdmissions')}</h2><div className="mt-3 space-y-2">{admissions.map((admission)=><article key={admission.id} className="rounded-lg border border-slate-200 p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{patientById.get(admission.patient_id)?.name??'—'}</p><p className="text-xs text-slate-600">{patientById.get(admission.patient_id)?.patient_identifier} · {wards.find((ward)=>ward.id===admission.ward_id)?.name} · {bedById.get(admission.bed_id)?.bed_label}</p></div>{admission.is_demo&&<span className="rounded-full bg-amber-100 px-2 py-1 text-xs">{t('demo')}</span>}</div><p className="mt-2 text-xs text-slate-500">{t('admittedAt')}: {formatHospitalDate(admission.admitted_at,org.timezone)}</p><button disabled={!can('admissions.manage')||busy} onClick={()=>{if(window.confirm(t('confirmDischarge')))void run('discharge_patient',{p_admission_id:admission.id});}} className="mt-2 min-h-9 rounded-md border px-3 text-xs font-semibold">{t('discharge')}</button></article>)}{admissions.length===0&&!loading&&<p className="py-6 text-center text-sm text-slate-600">{t('noCurrentAdmissions')}</p>}</div></section></div>
    {dialog&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-3"><form onSubmit={dialog==='admit'?admit:createWard} className="w-full max-w-lg space-y-3 rounded-xl bg-white p-5 shadow-xl"><h2 className="text-lg font-semibold">{dialog==='admit'?t('admitPatient'):t('addWard')}</h2>{dialog==='admit'?<><Select label={t('patient')} value={patientId} set={setPatientId} options={patients.map((item)=>({id:item.id,label:`${item.name} · ${item.patient_identifier}`}))}/><Select label={t('ward')} value={wardId} set={setWardId} options={wards.map((item)=>({id:item.id,label:item.name}))}/><Select label={t('bed')} value={bedId} set={setBedId} options={beds.filter((item)=>item.status==='available'&&(!wardId||item.ward_id===wardId)).map((item)=>({id:item.id,label:item.bed_label}))}/><Select label={t('doctor')} value={doctorId} set={setDoctorId} options={doctors.map((item)=>({id:item.id,label:item.doctor_name}))}/><label className="block text-sm">{t('reason')}<textarea value={reason} onChange={(event)=>setReason(event.target.value)} rows={2} className="mt-1 w-full rounded-md border p-3"/></label></>:<><label className="block text-sm">{t('wardName')}<input required value={wardName} onChange={(event)=>setWardName(event.target.value)} className="mt-1 h-11 w-full rounded-md border px-3"/></label><label className="block text-sm">{t('bedCount')}<input required min="1" max="200" type="number" value={bedCount} onChange={(event)=>setBedCount(event.target.value)} className="mt-1 h-11 w-full rounded-md border px-3"/></label></>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setDialog(null)} className="min-h-10 rounded-md border px-3">{t('cancel')}</button><button disabled={busy} className="min-h-10 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{t('save')}</button></div></form></div>}
  </div>;
}
function Select({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:Array<{id:string;label:string}>}){return <label className="block text-sm">{label}<select required value={value} onChange={(event)=>set(event.target.value)} className="mt-1 h-11 w-full rounded-md border px-3"><option value="">—</option>{options.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}
