'use client';

import { useEffect, useState } from 'react';
import { useTranslations } from 'next-intl';
import { supabase } from '@/lib/supabase-client';
import { useHospital } from '@/lib/hospital/HospitalProvider';
import { callRpc } from '@/lib/hospital/api';
import { StatusChip } from '@/components/hospital/ui-kit';
import { formatHospitalDate } from '@/lib/hospital/format';

type Staff={user_id:string;name:string;email:string;role:string;is_active:boolean;is_demo:boolean};
type PriorityRule={id:string;priority:string;target_max_wait_days:number;allowed_slot_kinds:string[];staff_approval_required:boolean};
const TABS=['organisation','verification','staff','hours','queue','priority','sample'] as const;

export function HospitalSettingsPage(){
  const t=useTranslations('hospitalOps');const legacy=useTranslations('hospital');const {org,can,refresh}=useHospital();
  const [tab,setTab]=useState<(typeof TABS)[number]>('organisation');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const [name,setName]=useState(org?.name??'');const [timezone,setTimezone]=useState(org?.timezone??'Asia/Kolkata');const [label,setLabel]=useState(org?.patient_id_label??'');const [prefix,setPrefix]=useState(org?.patient_id_prefix??'');
  const [settings,setSettings]=useState<Record<string,unknown>>((org?.settings??{}) as Record<string,unknown>);const [email,setEmail]=useState('');const [role,setRole]=useState('front_desk');const [staff,setStaff]=useState<Staff[]>([]);const [rules,setRules]=useState<PriorityRule[]>([]);const [holidays,setHolidays]=useState<Array<{id:string;holiday_date:string;name:string}>>([]);const [holidayName,setHolidayName]=useState('');const [holidayDate,setHolidayDate]=useState('');
  useEffect(()=>{if(org){setName(org.name);setTimezone(org.timezone);setLabel(org.patient_id_label);setPrefix(org.patient_id_prefix);setSettings((org.settings??{}) as Record<string,unknown>);}},[org]);
  useEffect(()=>{if(!org)return;void (async()=>{try{if(can('staff.manage'))setStaff(await callRpc<Staff[]>('list_hospital_staff',{p_hospital_id:org.id})??[]);const [ruleResult,holidayResult]=await Promise.all([supabase.from('priority_rules').select('*').eq('hospital_id',org.id),supabase.from('hospital_holidays').select('id,holiday_date,name').eq('hospital_id',org.id).order('holiday_date')]);if(ruleResult.error)throw ruleResult.error;if(holidayResult.error)throw holidayResult.error;const order=['emergency','clinically_priority','urgent','routine'];setRules(((ruleResult.data??[]) as PriorityRule[]).sort((a,b)=>order.indexOf(a.priority)-order.indexOf(b.priority)));setHolidays(holidayResult.data??[]);}catch(caught){setError(caught instanceof Error?caught.message:t('settingsLoadFailed'));}})();},[org,can,t]);
  const run=async(action:()=>Promise<unknown>,success?:string)=>{setBusy(true);setError('');setMessage('');try{await action();await refresh();if(success)setMessage(success);}catch(caught){setError(caught instanceof Error?caught.message:t('operationFailed'));}finally{setBusy(false);}};
  const saveOrg=()=>org&&void run(()=>callRpc('update_hospital_org',{p_hospital_id:org.id,p_name:name,p_timezone:timezone,p_patient_id_label:label,p_patient_id_prefix:prefix,p_settings:settings}),t('settingsSaved'));
  const invite=()=>org&&void run(async()=>{await callRpc('invite_hospital_staff',{p_hospital_id:org.id,p_email:email,p_staff_role:role});setEmail('');},t('inviteSent'));
  const changeActive=(member:Staff)=>org&&void run(()=>callRpc('set_member_active',{p_hospital_id:org.id,p_user_id:member.user_id,p_active:!member.is_active}),t('settingsSaved'));
  const requestVerification=()=>org&&void run(()=>callRpc('request_hospital_verification',{p_hospital_id:org.id}),t('verificationRequested'));
  const sample=(method:'load_demo_data'|'remove_demo_data')=>org&&void run(()=>callRpc(method,{p_hospital_id:org.id}),t('settingsSaved'));
  const saveSettings=()=>void saveOrg();
  const addHoliday=()=>org&&void run(async()=>{const {error:writeError}=await supabase.from('hospital_holidays').insert({hospital_id:org.id,holiday_date:holidayDate,name:holidayName});if(writeError)throw writeError;setHolidayDate('');setHolidayName('');},t('settingsSaved'));
  const saveRule=(item:PriorityRule)=>org&&void run(async()=>{const {error:writeError}=await supabase.from('priority_rules').update({target_max_wait_days:item.target_max_wait_days,allowed_slot_kinds:item.allowed_slot_kinds,staff_approval_required:item.staff_approval_required}).eq('hospital_id',org.id).eq('id',item.id);if(writeError)throw writeError;},t('settingsSaved'));
  if(!org)return null;
  return <div className="space-y-5"><header><h1 className="text-2xl font-semibold text-slate-950">{t('settingsTitle')}</h1><p className="mt-1 text-sm text-slate-600">{t('settingsDescription')}</p></header>
    <div className="flex gap-1 overflow-x-auto border-b">{TABS.map((key)=><button key={key} onClick={()=>setTab(key)} className={`min-h-11 shrink-0 border-b-2 px-3 text-sm font-semibold ${tab===key?'border-teal-800 text-teal-900':'border-transparent text-slate-600'}`}>{t(`settingsTab.${key}` as 'settingsTab.organisation')}</button>)}</div>
    {error&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{message&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}
    {tab==='organisation'&&<section className="max-w-2xl space-y-4 rounded-xl border border-slate-200 bg-white p-5"><Field label={t('renameHospital')} value={name} change={setName}/><Field label={t('timezone')} value={timezone} change={setTimezone}/><Field label={t('patientIdLabel')} value={label} change={setLabel}/><Field label={t('patientIdPrefix')} value={prefix} change={setPrefix}/><button onClick={saveOrg} disabled={busy||!can('config.manage')} className="min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white disabled:opacity-50">{t('saveSettings')}</button></section>}
    {tab==='verification'&&<section className="max-w-2xl rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{t('verification')}</h2><StatusChip code={org.verification_status}/></div><p className="mt-3 text-sm leading-6 text-slate-600">{t('verificationRequirements')}</p>{org.verification_requested_at&&<p className="mt-2 text-sm text-slate-600">{t('requestedAt')}: {formatHospitalDate(org.verification_requested_at,org.timezone,{dateStyle:'medium',timeStyle:'short'})}</p>}<button disabled={busy||!can('config.manage')||org.verification_status==='verified'} onClick={requestVerification} className="mt-4 min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white disabled:opacity-50">{t('requestVerification')}</button></section>}
    {tab==='staff'&&<div className="space-y-4"><form onSubmit={(event)=>{event.preventDefault();invite();}} className="flex flex-wrap gap-2 rounded-xl border bg-white p-4"><input required type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder={t('email')} className="h-11 min-w-52 flex-1 rounded-md border px-3 text-sm"/><select value={role} onChange={(event)=>setRole(event.target.value)} className="h-11 rounded-md border px-3 text-sm">{['hospital_admin','front_desk','nurse','doctor','lab_tech','radiology_tech','admissions_staff'].map((item)=><option key={item}>{item}</option>)}</select><button disabled={busy||!can('staff.manage')} className="min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white disabled:opacity-50">{t('sendInvite')}</button></form><div className="grid gap-3">{staff.map((member,index)=><article key={`${member.user_id}-${member.role}-${index}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4"><div><p className="font-semibold">{member.name}</p><p className="text-sm text-slate-600">{member.email} · {member.role} {member.is_demo&&`· ${t('demo')}`}</p></div><button disabled={busy||!can('staff.manage')} onClick={()=>changeActive(member)} className="min-h-10 rounded-md border px-3 text-sm">{member.is_active?t('deactivate'):t('activate')}</button></article>)}</div></div>}
    {tab==='hours'&&<section className="space-y-4 rounded-xl border bg-white p-4"><h2 className="font-semibold">{t('hoursHolidays')}</h2><form onSubmit={(event)=>{event.preventDefault();addHoliday();}} className="flex flex-wrap gap-2"><input required type="date" value={holidayDate} onChange={(event)=>setHolidayDate(event.target.value)} className="h-11 rounded-md border px-3"/><input required value={holidayName} onChange={(event)=>setHolidayName(event.target.value)} placeholder={t('holidayName')} className="h-11 min-w-44 flex-1 rounded-md border px-3"/><button disabled={busy||!can('config.manage')} className="min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{t('addHoliday')}</button></form><div className="divide-y">{holidays.map((holiday)=><p key={holiday.id} className="py-3 text-sm">{holiday.holiday_date} · {holiday.name}</p>)}</div></section>}
    {tab==='queue'&&<section className="grid max-w-3xl gap-4 rounded-xl border bg-white p-5 sm:grid-cols-2"><NumberSetting label={t('waitFactorLow')} value={Number(settings.wait_factor_low??0.75)} change={(value)=>setSettings({...settings,wait_factor_low:value})}/><NumberSetting label={t('waitFactorHigh')} value={Number(settings.wait_factor_high??1.4)} change={(value)=>setSettings({...settings,wait_factor_high:value})}/><NumberSetting label={t('delayMinutes')} value={Number(settings.session_delay_minutes??15)} change={(value)=>setSettings({...settings,session_delay_minutes:value})}/><NumberSetting label={t('offerHoldHours')} value={Number(settings.offer_hold_hours??24)} change={(value)=>setSettings({...settings,offer_hold_hours:value})}/><label className="text-sm">{t('notifyThresholds')}<input value={Array.isArray(settings.notify_thresholds)?(settings.notify_thresholds as number[]).join(','): '10,5'} onChange={(event)=>setSettings({...settings,notify_thresholds:event.target.value.split(',').map((item)=>Number(item.trim())).filter(Number.isFinite)})} className="mt-1 h-11 w-full rounded-md border px-3"/></label><NumberSetting label={t('slotHorizonDays')} value={Number(settings.slot_horizon_days??120)} change={(value)=>setSettings({...settings,slot_horizon_days:value})}/><button onClick={saveSettings} disabled={busy||!can('config.manage')} className="min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{t('saveSettings')}</button></section>}
    {tab==='priority'&&<div className="space-y-3">{rules.map((rule)=><article key={rule.id} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[1fr_1fr_2fr_auto] sm:items-end"><div><p className="font-semibold">{t(`status.${rule.priority}` as 'status.routine')}</p><p className="text-xs text-slate-500">{t('allowedSlotKinds')}: {rule.allowed_slot_kinds.join(', ')}</p></div><label className="text-sm">{t('maxWaitDays')}<input type="number" min="0" value={rule.target_max_wait_days} onChange={(event)=>setRules((current)=>current.map((item)=>item.id===rule.id?{...item,target_max_wait_days:Number(event.target.value)}:item))} className="mt-1 h-10 w-full rounded-md border px-3"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.staff_approval_required} onChange={(event)=>setRules((current)=>current.map((item)=>item.id===rule.id?{...item,staff_approval_required:event.target.checked}:item))}/>{t('staffApproval')}</label><button onClick={()=>saveRule(rule)} disabled={busy||!can('config.manage')} className="min-h-10 rounded-md border px-3 text-sm font-semibold">{t('save')}</button></article>)}</div>}
    {tab==='sample'&&<section className="max-w-2xl rounded-xl border border-amber-200 bg-white p-5"><h2 className="font-semibold text-slate-950">{t('sampleData')}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t('sampleDataWarning')}</p><p className="mt-2 text-sm">{org.demo_data_loaded?t('sampleDataOn'):t('noSampleData')}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||!can('config.manage')} onClick={()=>sample('load_demo_data')} className="min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white">{org.demo_data_loaded?t('resetSampleData'):t('loadSampleData')}</button>{org.demo_data_loaded&&<button disabled={busy} onClick={()=>sample('remove_demo_data')} className="min-h-11 rounded-md border border-rose-300 px-4 text-sm font-semibold text-rose-800">{t('removeSampleData')}</button>}</div></section>}
  </div>;
}
function Field({label,value,change}:{label:string;value:string;change:(value:string)=>void}){return <label className="block text-sm font-medium">{label}<input value={value} onChange={(event)=>change(event.target.value)} className="mt-1 h-11 w-full rounded-md border border-slate-300 px-3"/></label>}
function NumberSetting({label,value,change}:{label:string;value:number;change:(value:number)=>void}){return <label className="block text-sm">{label}<input type="number" step="0.05" value={value} onChange={(event)=>change(Number(event.target.value))} className="mt-1 h-11 w-full rounded-md border px-3"/></label>}
