'use client';

import { useCallback, useState } from 'react';
import { useTranslations } from 'next-intl';
import { useHospital } from '@/lib/hospital/HospitalProvider';
import { callRpc } from '@/lib/hospital/api';
import { useLiveData } from '@/lib/hospital/useLive';
import { formatWaitRange } from '@/lib/hospital/format';
import type { HospitalQueueState } from '@/types/hospital';
import { ErrorPanel, KpiCard, StatusChip } from '@/components/hospital/ui-kit';
import { Activity, Clock3, Play, UserPlus } from 'lucide-react';

type PatientMatch = { id: string; identifier: string; name: string };
const TABLES=['queue_entries','opd_sessions','hospital_appointments'];

export function HospitalQueueBoard({sessionId}:{sessionId:string}) {
  const t=useTranslations('hospitalOps');
  const {org,can}=useHospital();
  const [busy,setBusy]=useState(false);
  const [errorAction,setErrorAction]=useState<string|null>(null);
  const [showWalkIn,setShowWalkIn]=useState(false);
  const [patientQuery,setPatientQuery]=useState('');
  const [matches,setMatches]=useState<PatientMatch[]>([]);
  const [priorityEntry,setPriorityEntry]=useState<string|null>(null);
  const [priority,setPriority]=useState('2');
  const [reason,setReason]=useState('');
  const load=useCallback(()=>callRpc<HospitalQueueState>('get_queue_state',{p_session_id:sessionId}),[sessionId]);
  const {data,loading,technicalDetails,refresh}=useLiveData(load,{hospitalId:org?.id??'',tables:TABLES});

  const act=async(name:string,args:Record<string,unknown>)=>{setBusy(true);setErrorAction(null);try{await callRpc(name,args);await refresh();}catch(caught){setErrorAction(caught instanceof Error?caught.message:t('operationFailed'));}finally{setBusy(false);}};
  const searchPatients=async()=>{if(!org)return;try{const result=await callRpc<{patients:PatientMatch[]}>('search_hospital_patients',{p_hospital_id:org.id,p_query:patientQuery,p_limit:8});setMatches(result.patients??[]);}catch(caught){setErrorAction(caught instanceof Error?caught.message:t('searchFailed'));}};
  const addPatient=async(patient:PatientMatch)=>{if(!org)return;setBusy(true);try{await callRpc('check_in_and_queue',{p_hospital_id:org.id,p_patient_id:patient.id,p_session_id:sessionId,p_appointment_id:null,p_priority:3,p_reason:null});setShowWalkIn(false);setPatientQuery('');setMatches([]);await refresh();}catch(caught){setErrorAction(caught instanceof Error?caught.message:t('operationFailed'));}finally{setBusy(false);}};
  const savePriority=async()=>{if(!priorityEntry)return;await act('queue_set_priority',{p_entry_id:priorityEntry,p_priority:Number(priority),p_reason:reason});setPriorityEntry(null);setReason('');};
  if(loading&&!data)return <div className="space-y-3" role="status"><div className="h-44 animate-pulse rounded-xl bg-slate-100"/><div className="h-64 animate-pulse rounded-xl bg-slate-100"/></div>;
  if(!data)return <ErrorPanel message={t('loadQueueFailed')} technicalDetails={technicalDetails} onRetry={()=>void refresh()} retryLabel={t('retry')} detailsLabel={t('showTechnicalDetails')}/>;

  return <div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold text-slate-950">{data.session.doctor}</h1><p className="mt-1 text-sm text-slate-600">{data.session.department} · {t('room')} {data.session.room??'—'}</p><div className="mt-2"><StatusChip code={data.session.status}/></div></div><div className="flex gap-2">{can('queue.manage')&&<button disabled={busy||data.session.status!=='open'} onClick={()=>void act('call_next',{p_session_id:sessionId})} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-teal-800 px-4 text-sm font-semibold text-white disabled:opacity-50"><Play className="h-4 w-4"/>{t('callNext')}</button>}{can('patients.register')&&<button onClick={()=>setShowWalkIn(true)} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold"><UserPlus className="h-4 w-4"/>{t('addWalkIn')}</button>}</div></header>
    {errorAction&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{errorAction}</p>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard icon={Activity} label={t('currentlyServing')} value={data.serving.length?`#${data.serving[0].token}`:'—'} hint={data.serving[0]?.patient}/><KpiCard icon={Play} label={t('nextToken')} value={data.next_token?`#${data.next_token}`:'—'}/><KpiCard icon={Clock3} label={t('waiting')} value={data.waiting_count}/><KpiCard icon={Clock3} label={t('avgConsult')} value={data.avg_consult_min?`${Math.round(data.avg_consult_min)} min`:'—'}/></div>
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-950">{t('queueEntries')}</h2><span className="text-xs text-slate-500">{t('waitRangeDisclaimer')}</span></div>
      <div className="mt-3 hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs text-slate-600"><tr>{['token','patientId','name','priority','patientsAhead','estimatedWait','status','actions'].map((key)=><th key={key} className="px-3 py-3">{t(key as 'token')}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{data.entries.map((entry)=><tr key={entry.id}><td className="px-3 py-3 font-semibold">#{entry.token}</td><td className="px-3 py-3">{entry.identifier}</td><td className="px-3 py-3">{entry.patient}{entry.is_walk_in&&<span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-[11px]">{t('walkIn')}</span>}</td><td className="px-3 py-3"><StatusChip code={entry.priority===0?'emergency':entry.priority===1?'clinically_priority':entry.priority===2?'urgent':'routine'}/></td><td className="px-3 py-3">{entry.patients_ahead}</td><td className="px-3 py-3">{formatWaitRange(entry.est_low,entry.est_high,t('calculating'))}</td><td className="px-3 py-3"><StatusChip code={entry.status}/></td><td className="px-3 py-3"><EntryActions entry={entry} busy={busy} canManage={can('queue.manage')} t={t} act={act} onPriority={()=>setPriorityEntry(entry.id)}/></td></tr>)}</tbody></table></div>
      <div className="mt-3 grid gap-3 md:hidden">{data.entries.map((entry)=><article key={entry.id} className="rounded-lg border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold">#{entry.token} · {entry.patient}</p><p className="text-xs text-slate-600">{entry.identifier}</p></div><StatusChip code={entry.status}/></div><div className="mt-3 flex flex-wrap gap-2"><StatusChip code={entry.priority===0?'emergency':entry.priority===1?'clinically_priority':entry.priority===2?'urgent':'routine'}/><span className="text-xs text-slate-600">{t('patientsAhead')}: {entry.patients_ahead} · {formatWaitRange(entry.est_low,entry.est_high,t('calculating'))}</span></div><div className="mt-3"><EntryActions entry={entry} busy={busy} canManage={can('queue.manage')} t={t} act={act} onPriority={()=>setPriorityEntry(entry.id)}/></div></article>)}</div>
    </section>
    {showWalkIn&&<Modal title={t('addWalkIn')} close={()=>setShowWalkIn(false)}><div className="flex gap-2"><input value={patientQuery} onChange={(event)=>setPatientQuery(event.target.value)} placeholder={t('patientSearch')} className="h-11 min-w-0 flex-1 rounded-md border px-3 text-sm"/><button onClick={()=>void searchPatients()} className="min-h-11 rounded-md bg-teal-800 px-3 text-sm font-semibold text-white">{t('search')}</button></div><ul className="mt-3 divide-y">{matches.map((patient)=><li key={patient.id} className="flex items-center justify-between gap-3 py-3 text-sm"><span>{patient.name} · {patient.identifier}</span><button disabled={busy} onClick={()=>void addPatient(patient)} className="min-h-10 rounded-md border px-3 font-semibold">{t('checkInAndQueue')}</button></li>)}</ul></Modal>}
    {priorityEntry&&<Modal title={t('updatePriority')} close={()=>setPriorityEntry(null)}><label className="block text-sm font-medium">{t('priority')}<select value={priority} onChange={(event)=>setPriority(event.target.value)} className="mt-1 h-11 w-full rounded-md border px-3"><option value="0">{t('status.emergency')}</option><option value="1">{t('status.clinically_priority')}</option><option value="2">{t('status.urgent')}</option><option value="3">{t('status.routine')}</option></select></label><label className="mt-3 block text-sm font-medium">{t('reason')}<textarea required value={reason} onChange={(event)=>setReason(event.target.value)} className="mt-1 w-full rounded-md border p-3" rows={3}/></label><button disabled={busy||reason.trim().length<3} onClick={()=>void savePriority()} className="mt-3 min-h-11 rounded-md bg-teal-800 px-4 text-sm font-semibold text-white disabled:opacity-50">{t('save')}</button></Modal>}
  </div>;
}

function EntryActions({entry,busy,canManage,t,act,onPriority}:{entry:HospitalQueueState['entries'][number];busy:boolean;canManage:boolean;t:(key:any,values?:any)=>string;act:(name:string,args:Record<string,unknown>)=>Promise<void>;onPriority:()=>void}) {
  if(!canManage)return null;
  return <div className="flex flex-wrap gap-1">{entry.status==='called'&&<button disabled={busy} onClick={()=>void act('queue_start',{p_entry_id:entry.id})} className="min-h-9 rounded-md border px-2 text-xs font-semibold">{t('startConsult')}</button>}{entry.status==='in_consultation'&&<button disabled={busy} onClick={()=>void act('queue_complete',{p_entry_id:entry.id})} className="min-h-9 rounded-md border px-2 text-xs font-semibold">{t('complete')}</button>}{['waiting','called'].includes(entry.status)&&<><button disabled={busy} onClick={()=>{if(window.confirm(t('confirmSkip')))void act('queue_skip',{p_entry_id:entry.id,p_reason:t('skippedByStaff')});}} className="min-h-9 rounded-md border px-2 text-xs">{t('skip')}</button><button disabled={busy} onClick={()=>void act('queue_no_show',{p_entry_id:entry.id})} className="min-h-9 rounded-md border px-2 text-xs">{t('noShow')}</button><button onClick={onPriority} className="min-h-9 rounded-md border px-2 text-xs">{t('updatePriority')}</button></>}{entry.status==='skipped'&&<button disabled={busy} onClick={()=>void act('queue_requeue',{p_entry_id:entry.id})} className="min-h-9 rounded-md border px-2 text-xs">{t('requeue')}</button>}</div>;
}
function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-3"><section role="dialog" aria-modal="true" aria-label={title} className="w-full max-w-lg rounded-xl bg-white p-5 shadow-xl"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{title}</h2><button onClick={close} aria-label={title}>×</button></div>{children}</section></div>; }
